import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex gap-5 p-4 border-b border-4-8 border-b-black">
            <li className="text-3xl"><Link href="/">Home</Link></li>
            <li className="text-3xl"><Link href="/dashboard/settings">Settings</Link></li>
            <li className="text-3xl"><Link href="/dashboard/analytics">Analytics</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
