import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import ActiveLink from "./components/ActiveLink";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-5">
          <ActiveLink path="/">Home</ActiveLink>
          <ActiveLink path="/about">About</ActiveLink>
          <ActiveLink path="/dashboard">Dashboard</ActiveLink>
          <ActiveLink path="/contact">Contact</ActiveLink>
        </nav>
        {children}
      </body>
    </html>
  );
}
